### PR TITLE
Added sentry vision for human sentry buster

### PR DESCRIPTION
**Pull request by Kenzzer**
Added glow to sentry for sentry busters.
-The glow appears on red sentries when they are NOT carried, and appear on RED engies, if they carry their sentry.

### CODE REVIEW

**Review by Pelipoika — CHANGES_REQUESTED** [review]
int team = GetClientTeam(iSentry); is not valid
Remove useless check https://github.com/Pelipoika/TF2-Bot-Control/pull/7/commits/2338f4a551ec95e24355af8f1e02a9ca36d32c7e#diff-c2c9e1d3af9be01d49628571490e638bR608

**Comment by 404UserNotFound** [comment]
Shouldn't it be like...

TFTeam iTeam = GetClientTeam(iSentry);

as opposed to "int iTeam"?

**Comment by Pelipoika** [comment]
@404UserNotFound Using a client function on a sentry? :thinking:

**Comment by 404UserNotFound** [comment]
Oh I thought iSentry was for the buster. It's for the sentrygun. I see. Yeah, useless then :P

**Review by Pelipoika — APPROVED** [review]

**Comment by Benoist3012** [comment]
I actually copied the glow creation code from Stt that was copied from slender fortress and I forgot to adapt it to BC

**Pull request merged**
